name: Build Electron macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 可手动触发

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build macOS app
        run: yarn run build:mac  # 或你实际的构建命令，比如 electron-builder

      - name: Upload macOS build
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: dist/mac  # 可能是 dist/mac/*.dmg、.zip 或 .app
